-- WasteWise: таблицы в Supabase (Postgres) — те же, что в локальном SQLite (core/db.py → init_db).
--
-- Приложение применяет файлы из supabase/migrations/ само при запуске (core/pg.py → apply_migrations)
-- и отмечает их в таблице schema_migrations. Можно выполнить и вручную:
-- Supabase → SQL Editor → вставить этот файл → Run. Повторный запуск безопасен (IF NOT EXISTS).
-- Время хранится в UTC, без часового пояса — как в SQLite.

CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,                  -- только хэш (PBKDF2 + соль), сам пароль не хранится
    name     TEXT NOT NULL,
    school   TEXT NOT NULL DEFAULT '',
    points   INTEGER NOT NULL DEFAULT 0,
    created  TIMESTAMP NOT NULL DEFAULT date_trunc('second', timezone('utc', now()))
);

CREATE TABLE IF NOT EXISTS scans (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT REFERENCES users (id) ON DELETE CASCADE,   -- NULL — гость
    predicted  TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    corrected  TEXT,
    image_hash TEXT,                                             -- md5 фото: баллы за одно фото один раз
    date       TIMESTAMP NOT NULL DEFAULT date_trunc('second', timezone('utc', now()))
);
CREATE INDEX IF NOT EXISTS idx_scans_user_hash ON scans (user_id, image_hash);

CREATE TABLE IF NOT EXISTS quiz_results (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users (id) ON DELETE CASCADE,
    score   INTEGER NOT NULL,
    total   INTEGER NOT NULL,
    mode    TEXT NOT NULL,
    points  INTEGER NOT NULL DEFAULT 0,                          -- для лимита «баллы за 3 викторины в сутки»
    date    TIMESTAMP NOT NULL DEFAULT date_trunc('second', timezone('utc', now()))
);
CREATE INDEX IF NOT EXISTS idx_quiz_user_date ON quiz_results (user_id, date);

-- Supabase открывает таблицы схемы public через свой REST API, а ключ anon у проекта публичный.
-- RLS без единой политики закрывает этот доступ целиком. Приложение подключается как владелец
-- таблиц (роль postgres), на него RLS не действует.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE quiz_results ENABLE ROW LEVEL SECURITY;
